<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>LpdfEncryptPermissionsOnly</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="encrypt-open-password.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lpdf.csproj" />
  </ItemGroup>

</Project>
